base_images:
  eks:
    name: automation-flavors
    namespace: stackrox
    tag: eks-0.3.1
  ubi:
    name: ubi
    namespace: ocp
    tag: "8"
  ubi-minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  project_image:
    dockerfile_path: .openshift-ci/Dockerfile.build_root
images:
- build_args:
  - name: ROX_PRODUCT_BRANDING
    value: RHACS_BRANDING
  dockerfile_path: .openshift-ci/build/Dockerfile.build-main-and-bundle
  from: src
  to: main-bundle
- build_args:
  - name: ROX_PRODUCT_BRANDING
    value: RHACS_BRANDING
  dockerfile_path: .openshift-ci/build/Dockerfile.build-central-db-bundle
  from: src
  to: central-db-bundle
- build_args:
  - name: ROX_PRODUCT_BRANDING
    value: RHACS_BRANDING
  dockerfile_path: .openshift-ci/build/Dockerfile.build-operator-artifacts
  from: src
  to: operator-artifacts
- build_args:
  - name: ROX_PRODUCT_BRANDING
    value: RHACS_BRANDING
  dockerfile_path: Dockerfile.gen
  from: ubi-minimal
  inputs:
    main-bundle:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/image/rhel/.
  to: main
- dockerfile_path: Dockerfile
  inputs:
    main-bundle:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/image/roxctl/.
  to: roxctl
- build_args:
  - name: ROX_PRODUCT_BRANDING
    value: RHACS_BRANDING
  dockerfile_path: Dockerfile.gen
  from: ubi
  inputs:
    central-db-bundle:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/image/postgres/.
  to: central-db
- dockerfile_path: Dockerfile
  inputs:
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/docs/.
  to: docs
- build_args:
  - name: GO_VERSION
    value: 1.17.2
  - name: ROX_IMAGE_FLAVOR
    value: development_build
  dockerfile_path: operator/Dockerfile
  inputs:
    operator-artifacts:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/.
  to: operator-controller
- dockerfile_path: bundle.Dockerfile
  inputs:
    operator-artifacts:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/operator/.
  to: operator-bundle
- dockerfile_path: rhacs-operator-index.Dockerfile
  inputs:
    operator-artifacts:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/operator/build/index/.
  to: operator-bundle-index
- build_args:
  - name: ROX_PRODUCT_BRANDING
    value: RHACS_BRANDING
  - name: RACE_CONDITION_DEBUG
    value: "true"
  dockerfile_path: .openshift-ci/build/Dockerfile.build-main-and-bundle
  from: src
  to: main-rcd-bundle
- build_args:
  - name: ROX_PRODUCT_BRANDING
    value: RHACS_BRANDING
  dockerfile_path: Dockerfile.gen
  from: ubi-minimal
  inputs:
    main-rcd-bundle:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/stackrox/image/rhel/.
  to: main-rcd
promotion:
  excluded_images:
  - main-bundle
  - central-db-bundle
  - main-rcd-bundle
  - operator-artifacts
  namespace: stackrox
  tag: test-pr
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 4000Mi
test_binary_build_commands: .openshift-ci/dispatch.sh test-binary-build-commands
tests:
- as: push-images
  steps:
    test:
    - as: push
      commands: .openshift-ci/dispatch.sh push-images "RHACS_BRANDING"
      credentials:
      - mount_path: /tmp/secret/stackrox-stackrox-push
        name: stackrox-stackrox-push
        namespace: test-credentials
      dependencies:
      - env: MAIN_IMAGE
        name: main
      - env: ROXCTL_IMAGE
        name: roxctl
      - env: CENTRAL_DB_IMAGE
        name: central-db
      - env: PIPELINE_DOCS_IMAGE
        name: docs
      - env: MAIN_RCD_IMAGE
        name: main-rcd
      - env: OPERATOR_IMAGE
        name: operator-controller
      - env: OPERATOR_BUNDLE_IMAGE
        name: operator-bundle
      - env: OPERATOR_BUNDLE_INDEX_MAGE
        name: operator-bundle-index
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: eks-qa-e2e-tests
  optional: true
  steps:
    post:
    - as: eks-destroy
      commands: |
        /usr/bin/openshift-ci.sh destroy eks
      credentials:
      - mount_path: /tmp/vault/stackrox-automation-flavors
        name: stackrox-automation-flavors
        namespace: test-credentials
      from: eks
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
    pre:
    - as: eks-create
      commands: |
        /usr/bin/openshift-ci.sh create eks
      credentials:
      - mount_path: /tmp/vault/stackrox-automation-flavors
        name: stackrox-automation-flavors
        namespace: test-credentials
      from: eks
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
    test:
    - as: test
      commands: |
        .openshift-ci/dispatch.sh eks-qa-e2e-tests
      credentials:
      - mount_path: /tmp/vault/stackrox-stackrox-e2e-tests
        name: stackrox-stackrox-e2e-tests
        namespace: test-credentials
      - mount_path: /tmp/vault/stackrox-automation-flavors
        name: stackrox-automation-flavors
        namespace: test-credentials
      from: test-bin
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
  timeout: 5h0m0s
zz_generated_metadata:
  branch: gavin-stackrox-ROX-11701-onboard-EKS
  org: stackrox
  repo: stackrox
