build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: stackrox-stackrox-check
  commands: make -C ci-operator/config/stackrox/stackrox check
  container:
    from: src
  run_if_changed: ci-operator/(config|jobs)/stackrox/stackrox
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: stackrox-stackrox
