base_images:
  ubi:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: ubi
    namespace: ocp
    tag: "8"
images:
- dockerfile_path: Dockerfile
  from: ubi
  to: stackrox-osci-build
promotion:
  namespace: stackrox
  tag: latest
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 4000Mi
tests:
- as: check
  commands: echo "hello world"
  container:
    from: stackrox-osci-build
zz_generated_metadata:
  branch: master
  org: stackrox
  repo: stackrox-osci
