base_images:
  centos:
    name: centos
    namespace: origin
    tag: stream8
build_root:
  project_image:
    dockerfile_path: Dockerfile.build_root
images:
- dockerfile_path: Dockerfile
  from: centos
  to: stackrox-osci-build
promotion:
  namespace: stackrox
  tag: latest
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 4000Mi
tests:
- as: check
  commands: echo "hello world"
  container:
    from: stackrox-osci-build
zz_generated_metadata:
  branch: master
  org: stackrox
  repo: stackrox-osci
