base_images:
  centos:
    name: centos
    namespace: origin
    tag: stream8
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.15
images:
- dockerfile_literal: |-
    FROM quay.io/centos/centos:stream8
    RUN dnf upgrade -y && dnf clean all && rm -rf /var/cache/dnf
  from: centos
  to: quick-test
- context_dir: images
  dockerfile_path: rocksdb.Dockerfile
  from: centos
  to: rocksdb
- context_dir: images
  dockerfile_path: stackrox-build.Dockerfile
  inputs:
    centos:
      as:
      - base
    rocksdb:
      as:
      - builder
  to: stackrox-build
promotion:
  namespace: stackrox
  tag: latest
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: push-and-check-images
  steps:
    test:
    - as: push-and-check-quick-test
      commands: .openshift-ci/dispatch.sh push-check quick-test
      container:
        from: src
      credentials:
      - mount_path: /tmp/secret/stackrox-rox-ci-image
        name: stackrox-rox-ci-image
        namespace: test-credentials
      dependencies:
      - env: IMAGE
        name: quick-test
    - as: push-and-check-stackrox-build
      commands: .openshift-ci/dispatch.sh push-check stackrox-build
      container:
        from: src
      credentials:
      - mount_path: /tmp/secret/stackrox-rox-ci-image
        name: stackrox-rox-ci-image
        namespace: test-credentials
      dependencies:
      - env: IMAGE
        name: stackrox-build
zz_generated_metadata:
  branch: master
  org: stackrox
  repo: rox-ci-image-openshift-ci-mirror
